#This is properties file for pusher-backend
#created by : kotekaman
#created at : February, 18th 2019
[server]
port="3030"

[postgres]
url="localhost"
Port="5432"
db="postgres"
user="postgres"
password="postgres"

[twillio]
authToken="e8845a74ed47bc4d0f2c9d2c29761a63"
accountSid="ACb483b1cc20ace5bc8fd928f55504c063"
from="+17049355653"

[zensiva]
Userkey="u7znc3"
Passkey="KFTwxB4hrVm3tM5R"

[redis]
host="localhost"
port="6379"

[gcp]
bucket="hara-depo"
projectid="abiding-robot-271702"
filename="auth.json"

[aws]
region="ap-southeast-1"
bucketname="hara-depo-bucket"
