#This is properties file for pusher-backend
#created by : kotekaman
#created at : February, 18th 2019
[server]
port="3030"

[postgres]
url="localhost"
Port="5432"
db="postgres"
user="postgres"
password="postgres"



[redis]
host="localhost"
port="6379"

[gcp]
bucket="hara-depo"
projectid="abiding-robot-271702"
filename="auth.json"

[aws]
region="ap-southeast-1"
bucketname="hara-depo-bucket"
